# Generated by Django 4.1.1 on 2022-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='img_url',
            field=models.TextField(default=0, help_text='Pls enter an image url'),
            preserve_default=False,
        ),
    ]
